#!/bin/bash

shopt -s nocasematch
idx=0
cmplUrl=""
cmplFile=""

while [ $# -gt 0 ] ; do
	idx=$(($idx+1))
	
	if [[ $1 = "-cmplurl" ]] ; then
	  	shift 1
     	idx=$(($idx+1))
    	cmplUrl=$1
    elif [[ $1 = "-i" ]] ; then
     	shift 1
     	idx=$(($idx+1))
    	cmplFile=`echo $1 | tr ' ' '\ '`
   	elif  [ $idx -eq 1 ] && [ ! ${1:0:1} = "-" ]; then
    	cmplFile=`echo $1 | tr ' ' '\ '`
    else
    	pIdx=$(($pIdx+1))
       	cArg[$pIdx]=$1
    fi
  
  	shift 1
done

shopt -u nocasematch

if [ -z "$cmplUrl" ]  ; then
	if [ -n "$cmplFile" ] ; then
		arr=(`grep -i "cmplurl" "$cmplFile"`)
		if [ ! ${arr[0]:0:1} = "#" ]; then
			cmplUrl=${arr[2]}
		fi
	fi
fi

appname=cmpl
dirname="/usr/share/Cmpl"

coreFile="${dirname}/bin/libQtCore.so.4"
xmlFile="${dirname}/bin/libQtXml.so.4"

if (test -f $coreFile) && (test -f $xmlFile) ; then
	LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${dirname}/bin/"
	export LD_LIBRARY_PATH
fi

if [ -n "$cmplUrl" ] && [ -n "$cmplFile" ]  ; then
	export PYTHONPATH=/usr/share/Cmpl/pyCmpl
	export PYTHONSTARTUP=/usr/share/Cmpl/pyCmpl/pyCmpl/pyCmplShell.py
	export CMPLBINARY=/usr/share/Cmpl/cmpl
	
	python $dirname/pyCmpl/pyCmpl/cmplOnServer.py "$cmplFile" $cmplUrl "${cArg[1]}" "${cArg[2]}" "${cArg[3]}" "${cArg[4]}" "${cArg[5]}" "${cArg[6]}" "${cArg[7]}" "${cArg[8]}" "${cArg[9]}" "${cArg[10]}" "${cArg[11]}" "${cArg[12]}" "${cArg[13]}" "${cArg[14]}" "${cArg[15]}" "${cArg[16]}" "${cArg[17]}" "${cArg[18]}" "${cArg[19]}" "${cArg[20]}"

else 
	$dirname/bin/$appname  "$cmplFile" "${cArg[1]}" "${cArg[2]}" "${cArg[3]}" "${cArg[4]}" "${cArg[5]}" "${cArg[6]}" "${cArg[7]}" "${cArg[8]}" "${cArg[9]}" "${cArg[10]}" "${cArg[11]}" "${cArg[12]}" "${cArg[13]}" "${cArg[14]}" "${cArg[15]}" "${cArg[16]}" "${cArg[17]}" "${cArg[18]}" "${cArg[19]}" "${cArg[20]}"
fi











