#!/bin/bash
 
cd ..

echo "Install CMPL in /usr/share/Cmpl"

if test -d /usr/share/Cmpl ; then
   sudo rm -R /usr/share/Cmpl
fi

sudo cp -R Cmpl /usr/share/

if (test -f /usr/bin/cmpl) 
then 
	sudo rm /usr/bin/cmpl
fi

sudo ln -s /usr/share/Cmpl/cmpl /usr/bin/cmpl

sudo cp Cmpl/coliop /usr/bin
sudo chmod +x /usr/bin/coliop

sudo rm /usr/share/Cmpl/install

if [ -d Cmpl/pyCmpl ] ; then
	sudo cp Cmpl/pyCmpl/scripts/Unix/*  /usr/bin
fi

echo "Install CMPL done"
