#!/bin/bash

export PYTHONSTARTUP=/usr/local/lib/gurobi.py

argString=""

i=2  
while [ $i -le $# ]; do
	argString="${argString} ${!i}"
	i=$((i+1))
done

cd "$1"

/usr/bin/python2.6 gurobiCmpl.py ${argString}

