#!/bin/bash

cd ..

echo "Install CMPL in /Applictions/Cmpl"

if test -d /Applications/Cmpl ; then
    rm -R /Applications/Cmpl
fi

cp -R Cmpl /Applications
if (test -f /usr/bin/cmpl) 
then 
	sudo rm /usr/bin/cmpl
fi
sudo ln -s /Applications/Cmpl/bin/cmpl /usr/bin/cmpl
sudo cp Cmpl/coliop /usr/bin

rm /Applications/Cmpl/install
mv /Applications/Cmpl/coliop  /Applications/Cmpl/Coliop3/coliop 

if [ -d Cmpl/pyCmpl ] ; then
	sudo cp Cmpl/pyCmpl/scripts/Unix/*  /usr/bin
fi

echo "Install CMPL done"