#!/bin/bash
# This code is part of  CMPL  
#
# Copyright (C) 2007 - 2013 Thomas Schleiff - Halle(Saale), 
# Germany and Mike Steglich - Technical University of Applied Sciences
# Wildau, Germany 
#
# CMPL is a project of the Technical University of 
# Applied Sciences Wildau and the Institute for Operations Research 
# and Business Management at the Martin Luther University 
# Halle-Wittenberg.
# Please visit the project homepage <www.coliop.org>
# 
# CMPL is free software; you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by 
# the Free Software Foundation; either version 3 of the License, or 
# (at your option) any later version.
# 
# CMPL is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public 
# License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.
#
# @author  Mike Steglich - April 2013


# usage cmplMake
function usage () 
{
	if [ $oSystem == "win" ]; then 
		echo "Usage: make-cmpl [ test | clean | package ]"
	else
		echo "Usage: make-cmpl [ test | clean | package | install ]"
	fi
    echo " "
    echo "test                          - test routine "
    echo "clean                         - removes the obj and moc files in folder obj/"
    echo "package                       - creates a distribution package in folder Package/[linux/osx/win]"
    if [ $oSystem != "win" ]; then 
    	echo "install                       - installs CMPL"
    	echo "getExternals                  - downloads and builds OS,GLPK and Coliop"
    fi
    exit 1
}

oSystem="";
if [[ $OSTYPE == *darwin* ]] ; then 
	oSystem="osx"
elif  [[ $OSTYPE == *linux* ]] ; then
	oSystem="linux"
elif  [[ $OSTYPE == *msys* ]] ; then
	oSystem="win"
fi

if [ $oSystem == "" ] ; then
	echo "cmplMake error: Can not recognize your OS"
	exit 1
fi

if [ $# -gt 1 ] ; then
    usage
    exit 1
fi

if [ $# == 0 ] ; then 
	cd Cmpl 
	./cmplMake
	cd ..
fi

if [ $# == 1 ] ; then
	if [ $1 == "install" ]; then
		if [ $oSystem != "win" ]; then 
			if [ -d Package ]; then
				cd "Package/${oSystem}/Cmpl"
					./install
    			cd ..
    		else
    			echo "cmplMake error: Please create the CMPL package before installing"
    		fi
    	fi
    else 
		cd Cmpl
		./cmplMake $1
		cd ..
		if [ $1 == "package" ]; then
			if [ -d Cmpl/Package ] ; then 
				if [ -d Package ] ; then 
					rm -R Package
				fi
				mv Cmpl/Package .
			fi
			if [ $oSystem != "win" ]; then 
				rm pyCmpl/pyCmpl/*.pyc
			fi
			cp -R pyCmpl Package/$oSystem/Cmpl
			
			if [ -d pyCmpl/Thirdparty/pypy ] ; then 
				cp -R pyCmpl/Thirdparty/pypy Package/$oSystem/Cmpl/Thirdparty
			fi
			
			cp README Package/$oSystem/Cmpl
			cp AUTHORS Package/$oSystem/Cmpl
			
		elif [ $1 == "clean" ]; then
			rm pyCmpl/pyCmpl/*.pyc
		elif [ $1 == "test" ]; then
			cd pyCmpl/test
			./test-all
			cd ../..
		fi
		
	fi
fi

exit 0
