#############################################################################
# Makefile for building: bin/cmpl
# Generated by qmake (2.01a) (Qt 4.7.0) on: Do. Mrz 1 11:02:07 2012
# Project:  cmpl.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.7/mkspecs/macx-g++ -o Makefile cmpl.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DUNIX -DPROTO -DCHDIR -DSOLVERSERVICE -DQT_XML_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.7/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtXml.framework/Versions/4/Headers -I/usr/include/QtXml -I/usr/include -I. -Isrc/cmpl -Isrc/cmplUtil -Iobj -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtXml -L/tmp/qt-stuff-6474/source/qt-everywhere-opensource-src-4.7.0/lib -F/tmp/qt-stuff-6474/source/qt-everywhere-opensource-src-4.7.0/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/cmpl/Compiler.cc \
		src/cmpl/FileIO.cc \
		src/cmpl/Interpreter.cc \
		src/cmpl/IntFuncBase.cc \
		src/cmpl/IntFuncCode.cc \
		src/cmpl/IntFuncCtrl.cc \
		src/cmpl/IntFuncDef.cc \
		src/cmpl/IntFuncEnv.cc \
		src/cmpl/IntFuncIndex.cc \
		src/cmpl/IntFuncLine.cc \
		src/cmpl/IntFuncOper.cc \
		src/cmpl/IntFuncTerm.cc \
		src/cmpl/IntFuncValue.cc \
		src/cmpl/CmplCore.cc \
		src/cmpl/Tupelset.cc \
		src/cmpl/SetIter.cc \
		src/Cmpl.cc \
		src/cmplUtil/mprl.cc \
		src/cmplUtil/cfresult.cc \
		src/cmplUtil/CmplIOStream.cc \
		src/cmplUtil/CmplIO.cc \
		src/cmpl/_CMPL_Parser.cc \
		src/cmpl/_CMPL_Scanner.cc \
		src/cmplUtil/CmplArgs.cc \
		src/cmplUtil/CmplTools.cc \
		src/cmplUtil/ArgError.cc \
		src/cmplUtil/CmplFileType.cc \
		src/cmplUtil/CmplInstance.cc obj/moc_CmplIOStream.cpp \
		obj/moc_CmplIO.cpp
OBJECTS       = obj/Compiler.o \
		obj/FileIO.o \
		obj/Interpreter.o \
		obj/IntFuncBase.o \
		obj/IntFuncCode.o \
		obj/IntFuncCtrl.o \
		obj/IntFuncDef.o \
		obj/IntFuncEnv.o \
		obj/IntFuncIndex.o \
		obj/IntFuncLine.o \
		obj/IntFuncOper.o \
		obj/IntFuncTerm.o \
		obj/IntFuncValue.o \
		obj/CmplCore.o \
		obj/Tupelset.o \
		obj/SetIter.o \
		obj/Cmpl.o \
		obj/mprl.o \
		obj/cfresult.o \
		obj/CmplIOStream.o \
		obj/CmplIO.o \
		obj/_CMPL_Parser.o \
		obj/_CMPL_Scanner.o \
		obj/CmplArgs.o \
		obj/CmplTools.o \
		obj/ArgError.o \
		obj/CmplFileType.o \
		obj/CmplInstance.o \
		obj/moc_CmplIOStream.o \
		obj/moc_CmplIO.o
DIST          = /usr/local/Qt4.7/mkspecs/common/unix.conf \
		/usr/local/Qt4.7/mkspecs/common/mac.conf \
		/usr/local/Qt4.7/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.7/mkspecs/qconfig.pri \
		/usr/local/Qt4.7/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.7/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.7/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.7/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.7/mkspecs/features/debug.prf \
		/usr/local/Qt4.7/mkspecs/features/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.7/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.7/mkspecs/features/qt.prf \
		/usr/local/Qt4.7/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.7/mkspecs/features/moc.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.7/mkspecs/features/resources.prf \
		/usr/local/Qt4.7/mkspecs/features/uic.prf \
		/usr/local/Qt4.7/mkspecs/features/yacc.prf \
		/usr/local/Qt4.7/mkspecs/features/lex.prf \
		/usr/local/Qt4.7/mkspecs/features/include_source_dir.prf \
		cmpl.pro
QMAKE_TARGET  = cmpl
DESTDIR       = bin/
TARGET        = bin/cmpl

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cmpl.pro  /usr/local/Qt4.7/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.7/mkspecs/common/unix.conf \
		/usr/local/Qt4.7/mkspecs/common/mac.conf \
		/usr/local/Qt4.7/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.7/mkspecs/qconfig.pri \
		/usr/local/Qt4.7/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.7/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.7/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.7/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.7/mkspecs/features/debug.prf \
		/usr/local/Qt4.7/mkspecs/features/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.7/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.7/mkspecs/features/qt.prf \
		/usr/local/Qt4.7/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.7/mkspecs/features/moc.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.7/mkspecs/features/resources.prf \
		/usr/local/Qt4.7/mkspecs/features/uic.prf \
		/usr/local/Qt4.7/mkspecs/features/yacc.prf \
		/usr/local/Qt4.7/mkspecs/features/lex.prf \
		/usr/local/Qt4.7/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtXml.framework/QtXml.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Qt4.7/mkspecs/macx-g++ -o Makefile cmpl.pro
/usr/local/Qt4.7/mkspecs/common/unix.conf:
/usr/local/Qt4.7/mkspecs/common/mac.conf:
/usr/local/Qt4.7/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.7/mkspecs/qconfig.pri:
/usr/local/Qt4.7/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Qt4.7/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.7/mkspecs/features/qt_config.prf:
/usr/local/Qt4.7/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.7/mkspecs/features/default_pre.prf:
/usr/local/Qt4.7/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.7/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.7/mkspecs/features/debug.prf:
/usr/local/Qt4.7/mkspecs/features/default_post.prf:
/usr/local/Qt4.7/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.7/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.7/mkspecs/features/warn_on.prf:
/usr/local/Qt4.7/mkspecs/features/qt.prf:
/usr/local/Qt4.7/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.7/mkspecs/features/moc.prf:
/usr/local/Qt4.7/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.7/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.7/mkspecs/features/resources.prf:
/usr/local/Qt4.7/mkspecs/features/uic.prf:
/usr/local/Qt4.7/mkspecs/features/yacc.prf:
/usr/local/Qt4.7/mkspecs/features/lex.prf:
/usr/local/Qt4.7/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtXml.framework/QtXml.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.7/mkspecs/macx-g++ -o Makefile cmpl.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/cmpl1.0.0 || $(MKDIR) obj/cmpl1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/cmpl1.0.0/ && $(COPY_FILE) --parents src/cmpl/Compiler.hh src/cmpl/FileIO.hh src/cmpl/gen.h src/cmpl/gencode.h src/cmpl/genstart.h src/cmpl/gentext.h src/cmpl/Interpreter.hh src/cmpl/IntFuncBase.hh src/cmpl/IntFuncCode.hh src/cmpl/IntFuncCtrl.hh src/cmpl/IntFuncDef.hh src/cmpl/IntFuncEnv.hh src/cmpl/IntFuncIndex.hh src/cmpl/IntFuncLine.hh src/cmpl/IntFuncOper.hh src/cmpl/IntFuncTerm.hh src/cmpl/IntFuncValue.hh src/cmpl/CmplCore.hh src/cmpl/Tupelset.hh src/cmpl/SetIter.hh src/cmplUtil/mprl.hh src/cmplUtil/cfresult.hh src/cmplUtil/CmplException.hh src/cmplUtil/CmplIOStream.hh src/cmplUtil/CmplIO.hh src/cmpl/_CMPL_Parser.hh src/cmplUtil/CmplArgs.hh src/cmplUtil/CmplTools.hh src/cmplUtil/ArgError.hh src/cmplUtil/CmplFileType.hh src/cmplUtil/CmplInstance.hh obj/cmpl1.0.0/ && $(COPY_FILE) --parents src/cmpl/Compiler.cc src/cmpl/FileIO.cc src/cmpl/Interpreter.cc src/cmpl/IntFuncBase.cc src/cmpl/IntFuncCode.cc src/cmpl/IntFuncCtrl.cc src/cmpl/IntFuncDef.cc src/cmpl/IntFuncEnv.cc src/cmpl/IntFuncIndex.cc src/cmpl/IntFuncLine.cc src/cmpl/IntFuncOper.cc src/cmpl/IntFuncTerm.cc src/cmpl/IntFuncValue.cc src/cmpl/CmplCore.cc src/cmpl/Tupelset.cc src/cmpl/SetIter.cc src/Cmpl.cc src/cmplUtil/mprl.cc src/cmplUtil/cfresult.cc src/cmplUtil/CmplIOStream.cc src/cmplUtil/CmplIO.cc src/cmpl/_CMPL_Parser.cc src/cmpl/_CMPL_Scanner.cc src/cmplUtil/CmplArgs.cc src/cmplUtil/CmplTools.cc src/cmplUtil/ArgError.cc src/cmplUtil/CmplFileType.cc src/cmplUtil/CmplInstance.cc obj/cmpl1.0.0/ && (cd `dirname obj/cmpl1.0.0` && $(TAR) cmpl1.0.0.tar cmpl1.0.0 && $(COMPRESS) cmpl1.0.0.tar) && $(MOVE) `dirname obj/cmpl1.0.0`/cmpl1.0.0.tar.gz . && $(DEL_FILE) -r obj/cmpl1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: obj/moc_CmplIOStream.cpp obj/moc_CmplIO.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) obj/moc_CmplIOStream.cpp obj/moc_CmplIO.cpp
obj/moc_CmplIOStream.cpp: src/cmplUtil/CmplIO.hh \
		src/cmplUtil/CmplException.hh \
		src/cmplUtil/mprl.hh \
		src/cmplUtil/cfresult.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmplUtil/CmplInstance.hh \
		src/cmpl/FileIO.hh \
		src/cmpl/IntFuncBase.hh \
		src/cmplUtil/CmplIOStream.hh
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/cmplUtil/CmplIOStream.hh -o obj/moc_CmplIOStream.cpp

obj/moc_CmplIO.cpp: src/cmplUtil/CmplException.hh \
		src/cmplUtil/mprl.hh \
		src/cmplUtil/cfresult.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmplUtil/CmplInstance.hh \
		src/cmpl/FileIO.hh \
		src/cmpl/IntFuncBase.hh \
		src/cmplUtil/CmplIO.hh
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/cmplUtil/CmplIO.hh -o obj/moc_CmplIO.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

obj/Compiler.o: src/cmpl/Compiler.cc src/cmpl/Compiler.hh \
		src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmpl/gencode.h \
		src/cmpl/_CMPL_Parser.hh \
		src/cmpl/stack.hh \
		src/cmpl/location.hh \
		src/cmpl/position.hh \
		src/cmpl/FileIO.hh \
		src/cmpl/IntFuncBase.hh \
		src/cmplUtil/CmplInstance.hh \
		src/cmplUtil/CmplException.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Compiler.o src/cmpl/Compiler.cc

obj/FileIO.o: src/cmpl/FileIO.cc src/cmpl/FileIO.hh \
		src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmpl/IntFuncBase.hh \
		src/cmplUtil/CmplInstance.hh \
		src/cmplUtil/CmplException.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/FileIO.o src/cmpl/FileIO.cc

obj/Interpreter.o: src/cmpl/Interpreter.cc src/cmpl/Interpreter.hh \
		src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmpl/gencode.h \
		src/cmpl/IntFuncBase.hh \
		src/cmpl/FileIO.hh \
		src/cmplUtil/CmplInstance.hh \
		src/cmplUtil/CmplException.hh \
		src/cmpl/Compiler.hh \
		src/cmpl/_CMPL_Parser.hh \
		src/cmpl/stack.hh \
		src/cmpl/location.hh \
		src/cmpl/position.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Interpreter.o src/cmpl/Interpreter.cc

obj/IntFuncBase.o: src/cmpl/IntFuncBase.cc src/cmpl/IntFuncBase.hh \
		src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmpl/FileIO.hh \
		src/cmplUtil/CmplInstance.hh \
		src/cmplUtil/CmplException.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/IntFuncBase.o src/cmpl/IntFuncBase.cc

obj/IntFuncCode.o: src/cmpl/IntFuncCode.cc src/cmpl/IntFuncCode.hh \
		src/cmpl/IntFuncBase.hh \
		src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmpl/FileIO.hh \
		src/cmplUtil/CmplInstance.hh \
		src/cmplUtil/CmplException.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/IntFuncCode.o src/cmpl/IntFuncCode.cc

obj/IntFuncCtrl.o: src/cmpl/IntFuncCtrl.cc src/cmpl/IntFuncCtrl.hh \
		src/cmpl/IntFuncBase.hh \
		src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmpl/FileIO.hh \
		src/cmplUtil/CmplInstance.hh \
		src/cmplUtil/CmplException.hh \
		src/cmpl/gencode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/IntFuncCtrl.o src/cmpl/IntFuncCtrl.cc

obj/IntFuncDef.o: src/cmpl/IntFuncDef.cc src/cmpl/IntFuncDef.hh \
		src/cmpl/IntFuncBase.hh \
		src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmpl/FileIO.hh \
		src/cmplUtil/CmplInstance.hh \
		src/cmplUtil/CmplException.hh \
		src/cmpl/gencode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/IntFuncDef.o src/cmpl/IntFuncDef.cc

obj/IntFuncEnv.o: src/cmpl/IntFuncEnv.cc src/cmpl/IntFuncEnv.hh \
		src/cmpl/IntFuncBase.hh \
		src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmpl/FileIO.hh \
		src/cmplUtil/CmplInstance.hh \
		src/cmplUtil/CmplException.hh \
		src/cmpl/gencode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/IntFuncEnv.o src/cmpl/IntFuncEnv.cc

obj/IntFuncIndex.o: src/cmpl/IntFuncIndex.cc src/cmpl/IntFuncIndex.hh \
		src/cmpl/IntFuncBase.hh \
		src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmpl/FileIO.hh \
		src/cmplUtil/CmplInstance.hh \
		src/cmplUtil/CmplException.hh \
		src/cmpl/gencode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/IntFuncIndex.o src/cmpl/IntFuncIndex.cc

obj/IntFuncLine.o: src/cmpl/IntFuncLine.cc src/cmpl/IntFuncLine.hh \
		src/cmpl/IntFuncBase.hh \
		src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmpl/FileIO.hh \
		src/cmplUtil/CmplInstance.hh \
		src/cmplUtil/CmplException.hh \
		src/cmpl/gencode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/IntFuncLine.o src/cmpl/IntFuncLine.cc

obj/IntFuncOper.o: src/cmpl/IntFuncOper.cc src/cmpl/IntFuncOper.hh \
		src/cmpl/IntFuncBase.hh \
		src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmpl/FileIO.hh \
		src/cmplUtil/CmplInstance.hh \
		src/cmplUtil/CmplException.hh \
		src/cmpl/gencode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/IntFuncOper.o src/cmpl/IntFuncOper.cc

obj/IntFuncTerm.o: src/cmpl/IntFuncTerm.cc src/cmpl/IntFuncTerm.hh \
		src/cmpl/IntFuncBase.hh \
		src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmpl/FileIO.hh \
		src/cmplUtil/CmplInstance.hh \
		src/cmplUtil/CmplException.hh \
		src/cmpl/Compiler.hh \
		src/cmpl/gencode.h \
		src/cmpl/_CMPL_Parser.hh \
		src/cmpl/stack.hh \
		src/cmpl/location.hh \
		src/cmpl/position.hh \
		src/cmpl/Interpreter.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/IntFuncTerm.o src/cmpl/IntFuncTerm.cc

obj/IntFuncValue.o: src/cmpl/IntFuncValue.cc src/cmpl/IntFuncValue.hh \
		src/cmpl/IntFuncBase.hh \
		src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmpl/FileIO.hh \
		src/cmplUtil/CmplInstance.hh \
		src/cmplUtil/CmplException.hh \
		src/cmpl/gencode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/IntFuncValue.o src/cmpl/IntFuncValue.cc

obj/CmplCore.o: src/cmpl/CmplCore.cc src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmpl/FileIO.hh \
		src/cmpl/IntFuncBase.hh \
		src/cmplUtil/CmplInstance.hh \
		src/cmplUtil/CmplException.hh \
		src/cmpl/Compiler.hh \
		src/cmpl/gencode.h \
		src/cmpl/_CMPL_Parser.hh \
		src/cmpl/stack.hh \
		src/cmpl/location.hh \
		src/cmpl/position.hh \
		src/cmpl/Interpreter.hh \
		src/cmpl/IntFuncCode.hh \
		src/cmpl/IntFuncEnv.hh \
		src/cmpl/IntFuncValue.hh \
		src/cmpl/IntFuncDef.hh \
		src/cmpl/IntFuncIndex.hh \
		src/cmpl/IntFuncOper.hh \
		src/cmpl/IntFuncCtrl.hh \
		src/cmpl/IntFuncLine.hh \
		src/cmpl/IntFuncTerm.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/CmplCore.o src/cmpl/CmplCore.cc

obj/Tupelset.o: src/cmpl/Tupelset.cc src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmpl/IntFuncBase.hh \
		src/cmpl/FileIO.hh \
		src/cmplUtil/CmplInstance.hh \
		src/cmplUtil/CmplException.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Tupelset.o src/cmpl/Tupelset.cc

obj/SetIter.o: src/cmpl/SetIter.cc src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmpl/IntFuncBase.hh \
		src/cmpl/FileIO.hh \
		src/cmplUtil/CmplInstance.hh \
		src/cmplUtil/CmplException.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/SetIter.o src/cmpl/SetIter.cc

obj/Cmpl.o: src/Cmpl.cc src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmplUtil/CmplInstance.hh \
		src/cmplUtil/CmplException.hh \
		src/cmplUtil/CmplIO.hh \
		src/cmplUtil/mprl.hh \
		src/cmplUtil/cfresult.hh \
		src/cmpl/FileIO.hh \
		src/cmpl/IntFuncBase.hh \
		src/cmplUtil/CmplIOStream.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Cmpl.o src/Cmpl.cc

obj/mprl.o: src/cmplUtil/mprl.cc src/cmplUtil/mprl.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/mprl.o src/cmplUtil/mprl.cc

obj/cfresult.o: src/cmplUtil/cfresult.cc src/cmplUtil/cfresult.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmplUtil/CmplInstance.hh \
		src/cmplUtil/CmplException.hh \
		src/cmpl/FileIO.hh \
		src/cmpl/IntFuncBase.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cfresult.o src/cmplUtil/cfresult.cc

obj/CmplIOStream.o: src/cmplUtil/CmplIOStream.cc src/cmplUtil/CmplIOStream.hh \
		src/cmplUtil/CmplIO.hh \
		src/cmplUtil/CmplException.hh \
		src/cmplUtil/mprl.hh \
		src/cmplUtil/cfresult.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmplUtil/CmplInstance.hh \
		src/cmpl/FileIO.hh \
		src/cmpl/IntFuncBase.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/CmplIOStream.o src/cmplUtil/CmplIOStream.cc

obj/CmplIO.o: src/cmplUtil/CmplIO.cc src/cmplUtil/CmplIO.hh \
		src/cmplUtil/CmplException.hh \
		src/cmplUtil/mprl.hh \
		src/cmplUtil/cfresult.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmplUtil/CmplInstance.hh \
		src/cmpl/FileIO.hh \
		src/cmpl/IntFuncBase.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/CmplIO.o src/cmplUtil/CmplIO.cc

obj/_CMPL_Parser.o: src/cmpl/_CMPL_Parser.cc src/cmpl/_CMPL_Parser.hh \
		src/cmpl/stack.hh \
		src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmpl/location.hh \
		src/cmpl/position.hh \
		src/cmpl/Compiler.hh \
		src/cmpl/gencode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/_CMPL_Parser.o src/cmpl/_CMPL_Parser.cc

obj/_CMPL_Scanner.o: src/cmpl/_CMPL_Scanner.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/_CMPL_Scanner.o src/cmpl/_CMPL_Scanner.cc

obj/CmplArgs.o: src/cmplUtil/CmplArgs.cc src/cmplUtil/CmplArgs.hh \
		src/cmpl/gentext.h \
		src/cmplUtil/CmplTools.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/CmplArgs.o src/cmplUtil/CmplArgs.cc

obj/CmplTools.o: src/cmplUtil/CmplTools.cc src/cmplUtil/CmplTools.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/CmplTools.o src/cmplUtil/CmplTools.cc

obj/ArgError.o: src/cmplUtil/ArgError.cc src/cmplUtil/ArgError.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ArgError.o src/cmplUtil/ArgError.cc

obj/CmplFileType.o: src/cmplUtil/CmplFileType.cc src/cmplUtil/CmplFileType.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/CmplFileType.o src/cmplUtil/CmplFileType.cc

obj/CmplInstance.o: src/cmplUtil/CmplInstance.cc src/cmplUtil/CmplInstance.hh \
		src/cmpl/CmplCore.hh \
		src/cmpl/gen.h \
		src/cmpl/gentext.h \
		src/cmpl/genstart.h \
		src/cmplUtil/CmplArgs.hh \
		src/cmplUtil/CmplTools.hh \
		src/cmplUtil/ArgError.hh \
		src/cmplUtil/CmplFileType.hh \
		src/cmpl/SetIter.hh \
		src/cmpl/Tupelset.hh \
		src/cmplUtil/CmplException.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/CmplInstance.o src/cmplUtil/CmplInstance.cc

obj/moc_CmplIOStream.o: obj/moc_CmplIOStream.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_CmplIOStream.o obj/moc_CmplIOStream.cpp

obj/moc_CmplIO.o: obj/moc_CmplIO.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_CmplIO.o obj/moc_CmplIO.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

