#!/bin/bash
 
cd ..

echo "Download the OSSolverService binary [y/n]"
read -n 1 osDownload
if [ $osDownload = "y" -o $osDownload = "Y" ] ; then 

	osSolverFile=OSSolverService-2.3.5-linux-x86-gcc4.4.1
	osSolverUrl=http://www.coin-or.org/download/binary/OS/OSSolverService/

	wgetcmd=wget
	wgetcount=`which wget 2>/dev/null | wc -w`
	if test ! $wgetcount = 1; then
  	echo "Utility wget not found in your PATH."
  	if test `uname` = Darwin; then
   		wgetcmd=ftp
  		echo "Using ftp command instead."
  	else
    	exit -1
  	fi
	fi


	echo "Download OSSolverService"
	$wgetcmd ${osSolverUrl}${osSolverFile}.zip

	if [ -f "${osSolverFile}.zip" ] ; then
		gunzip -S .zip  ${osSolverFile}.zip
		chmod +x ${osSolverFile}
	else
		echo "Can't find ${osSolverFile}.zip"
		exit 1
	fi

	./${osSolverFile} -v 2>osStdErr
	if  test -s osStdErr ;  then
		echo "Can't execute /usr/bin/OSSolverService"
		echo "Please check, whether the gFortran library libgfortran.so.3 is installed"
		echo "Installation is canceled"
		exit 1
	fi

	echo "Install /usr/bin/OSSolverService"
	sudo mv ${osSolverFile} /usr/bin/OSSolverService
	
	echo "OSSolverServicePath = /usr/bin/" >Cmpl/bin/cmpl.opt

else
	echo "Please edit the path of the OSSolverService binary in the file cmpl.opt."
fi 

echo "Install CMPL"

if test -d /usr/share/Cmpl ; then
   sudo rm -R /usr/share/Cmpl
fi

sudo cp -R Cmpl /usr/share/

coreFile="/usr/lib/libQtCore.so.4"
xmlFile="/usr/lib/libQtXml.so.4"
coreFile64="/usr/lib64/libQtCore.so.4"
xmlFile64="/usr/lib64/libQtXml.so.4"
if  ( (test -f $coreFile) && (test -f $xmlFile) ) || ( (test -f $coreFile64) && (test -f $xmlFile64) )  ; then
   	sudo rm /usr/share/Cmpl/bin/libQtCore.so.4 
   	sudo rm /usr/share/Cmpl/bin/libQtXml.so.4 
fi

sudo cp Cmpl/cmpl /usr/bin
sudo chmod +x /usr/bin/cmpl
sudo rm /usr/share/Cmpl/install

echo "Install CMPL done"
