#!/bin/bash

cd ..

echo "Download the OSSolverService binary [y/n]"
read -n 1 osDownload
if [ $osDownload = "y" -o $osDownload = "Y" ] ; then 
	osSolverFile=OSSolverService-2.3.5-macosx-ix86_64-gcc.4.2.1
	osSolverUrl=http://www.coin-or.org/download/binary/OS/OSSolverService/

	wgetcmd=wget
	wgetcount=`which wget 2>/dev/null | wc -w`
	if test ! $wgetcount = 1; then
 	echo "Utility wget not found in your PATH."
  	if test `uname` = Darwin; then
   		wgetcmd=ftp
    	echo "Using ftp command instead."
  	else
    	exit -1
  	fi
	fi


	echo "Download OSSolverService"
	$wgetcmd ${osSolverUrl}${osSolverFile}.zip

	if [ -f "${osSolverFile}.zip" ] ; then
		gunzip -S .zip  ${osSolverFile}.zip
		chmod +x ${osSolverFile}
	else
		echo "Can't find ${osSolverFile}.zip"
		exit 1
	fi

	./${osSolverFile} -v 2>osStdErr
	if  test -s osStdErr ;  then
		echo "Can't execute /usr/bin/OSSolverService"
		echo "Installation is canceled"
		exit 1
	fi

	echo "Install /usr/bin/OSSolverService"
	sudo mv ${osSolverFile} /usr/bin/OSSolverService
	
	echo "OSSolverServicePath = /usr/bin/" >Cmpl/bin/cmpl.opt

else
	echo "Please edit the path of the OSSolverService binary in the file cmpl.opt."
fi 


echo "Install CMPL in /Applictions/Cmpl"

if test -d /Applications/Cmpl ; then
    rm -R /Applications/Cmpl
fi

cp -R Cmpl /Applications
sudo cp Cmpl/cmpl /usr/bin

if (test -d /Library/Frameworks/QtXml.framework/) || (test -d /Library/Frameworks/QtCore.framework/) 
then 
	rm -R /Applications/Cmpl/Frameworks
fi 

rm /Applications/Cmpl/install

echo "Install CMPL done"