#!/bin/bash

if  [[ $OSTYPE == *msys* ]] ; then
	export PythonBin=$PWD/../../Cmpl/Thirdparty/pypy/pypy $*
else
	export PythonBin=python 
fi



echo "######### start pyCmpl tests #############################"
./test-pyCmpl diet.py testStdOut
./test-pyCmpl complex-method.py	testStdOut
#./test-pyCmpl cut.py testStdOut
./test-pyCmpl assignment.py testStdOut
./test-pyCmpl transportation.py testStdOut
./test-pyCmpl prodmix.py testStdOut

if  [[ $OSTYPE != *msys* ]] ; then
	./cmplServerTest -start 9999
	./test-pyCmpl assignment-remote.py ingnoreStdOut
	./cmplServerTest -stop 9999
fi 

echo "######### pyCmpl tests done #############################"
